env:
  global:
  - CC_TEST_REPORTER_ID=5d49665b67fb0a589b7bfe884f8dfdf1188f6256bdd35fb288463fa913869005
language: node_js
node_js:
- stable
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
  - node_modules
before_script:
- npm install
- psql -c '\i src/migrations/database.sql \q' -U postgres
- psql -c "CREATE ROLE bootcamp47 WITH LOGIN PASSWORD 'lovely' CREATEDB SUPERUSER;" -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test
- npm run coveralls
- npm run codeClimate
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
